name: FTPCICDforReact
on: [ push, pull_request]
jobs:
  build:
    env:
      subdomain: ${{ secrets.STAGING_SUDOKU_WEB_SUBDOMAIN }}
      username: ${{ secrets.STAGING_SUDOKU_WEB_USERNAME }}
      password: ${{ secrets.STAGING_SUDOKU_WEB_PASSWORD }}
    runs-on: ubuntu-latest
    outputs:
      TRANCH: ${{ steps.get_tranch.outputs.TRANCH_NAME }}
    steps:
      - uses: actions/checkout@v2
      - name: Get branch/tag name for ftp folder
        id: get_tranch
        uses: JoyJulianGomes/github-action-react-ci-ftp-cd/branchname@master
      - name: follow up
        shell: bash
        run: |
          echo ${{ steps.get_tranch.outputs.TRANCH_NAME }}
          echo ${{ env.subdomain }}
          echo ${{ env.username }}
          echo ${{ env.password }}
      - name: modify package.json
        shell: bash
        run: |
          pwd
          ls
          node ./.github/workflows/homepageaddress.js ${{ env.subdomain }} ${{ steps.get_tranch.outputs.TRANCH_NAME }}
      - name: build react app
        shell: bash
        run: |
          mkdir build
          cp package.json build/package.json
      - name: upload build
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.STAGING_SUDOKU_WEB_SERVER }}
          user: ${{ secrets.STAGING_SUDOKU_WEB_USERNAME }}
          password: ${{ secrets.STAGING_SUDOKU_WEB_PASSWORD }}
          localDir: "build/"
          remoteDir: ${{ steps.get_tranch.outputs.TRANCH_NAME }}
  