# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [ push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # - id: get_branch_name
      #   uses: JoyJulianGomes/github-action-react-ci-ftp-cd/branchname@master
      # - id: get_folder_name
      #   uses: JoyJulianGomes/github-action-react-ci-ftp-cd/ftpupload@master
      #   with:
      #     ftphost: "ftphost"
      #     ftpuser: "ftpuser"
      #     ftppassword: "ftppassword"
      #     branchname: "branchname"
      #     domain_prefix: "domain_prefix"
      # - run: | 
      #       echo ${{ steps.get_branch_name.outputs.TRANCH_NAME }} 
      #       echo ${{ steps.get_folder_name.outputs.upload_folder }} 
      #   shell: bash
      - name: Get the version
        id: get_version
        run: |
          version=$(echo ${GITHUB_REF////-} | cut --fields="3-" --delimiter='-')
          echo $GITHUB_REF
          echo $version
          echo ::set-output name=VERSION::$version
        shell: bash
  job2:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - run: |
        v=$(echo ${GITHUB_REF////-} | cut --fields="3-" --delimiter='-')
        echo $GITHUB_REF
        echo $v
        echo ${{needs.build.outputs.version}}